### ISSUE TITLE
How to prepare the dataset

### ISSUE THREAD

**Issue by nessessence** [SivanDoveh/DAC#1]
Hi, I love your work and would like to reproduce the result. 
However, the csv file map that you provided, train_with_cap.csv and also the whole quality caption folder in https://drive.google.com/drive/folders/1DmHeV8oWiMwtkaTH-nruMyjBiuJvcwnv, have a different set of image names than my downloaded cc3m. 
Could you provide the code that you use to download and prepare the dataset?

thank you

**Comment by SivanDoveh** [comment]
Hi! thanks a lot!
I'm sorry for the confusion- I named the quality captions with the image name they are describing. 
I will try to load the code of creation later this month
