### ISSUE TITLE
Location on SVLC negative caption generation

### ISSUE THREAD

**Issue by Kenan-jeff-Jiang** [SivanDoveh/DAC#2]
Hi :) 👍 
Thank you so much for sharing this amazing repository. I thoroughly enjoyed exploring your work—it’s truly impressive!

I’m planning to conduct some experiments based on your implementation and was going through the resources and URLs provided in the README. However, I’m a bit confused about the location of the negative captions used in training.

I have checked the below 2 URLs you shared:
https://drive.google.com/drive/folders/1DmHeV8oWiMwtkaTH-nruMyjBiuJvcwnv
https://drive.google.com/drive/folders/1WosT_kdam1ymWjVSK2ezyydLoqmm0LdX
From these, I could only find the quality and dense captions but couldn’t locate the negative captions.

Could you kindly direct me to the download location for the negative captions? Apologies in advance if they are already in the repo and I’ve somehow missed them! If the negative captions are not included by design, I’d appreciate it if you could confirm that as well so I can plan to generate them myself.

Thank you again for your time and for making this fantastic work accessible to everyone. Your assistance would mean a lot!

**Comment by SivanDoveh** [comment]
The negatives are created on the fly with the flags --mil_dense_negs --vl_negs --neg_type rand_both --auto_neg_types NOUN ADP ADJ VERB
